GET http://localhost:3010/api/category HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkYjRiMzUxLTJjNzUtNDVlMi04ZGUzLTc1OGI2MDIyY2U5YSIsInVzZXJuYW1lIjoidXNlciIsImlhdCI6MTY0MjYxMzU4OSwiZXhwIjoxNjQyNjEzNzA5fQ.EQjxT7uxHni6nRXH7wc9WmIyTgJfjb96gwWQQgZBU4Y
